import type { Metadata } from "next";
import ReactQueryProvider from "@/components/providers/ReactQueryProvider";
import { Toaster } from "@/components/ui/sonner";
import { margarine, quicksand, chewy, umoe } from "./fonts";
import "./globals.css";
import "@/styles/fonts.css";
import "@/animations/bubble-shake.css";

import { SectionThemeProvider } from "@/components/providers/SectionThemeProvider";

export const metadata: Metadata = {
  title: "Tiny Gong POS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${margarine.variable} ${quicksand.variable} ${chewy.variable} ${umoe.variable} antialiased `}
      >
        <ReactQueryProvider>
          <SectionThemeProvider defaultSection="workspace">
            {children}
            <Toaster richColors />
          </SectionThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
